[phases.setup]
aptPkgs = [
  "bash",
  "build-essential",
  "pkg-config",

  "libcairo2-dev",
  "libpango1.0-dev",
  "libgdk-pixbuf-2.0-dev",
  "libffi-dev",

  "libxcb1-dev",
  "libxcb-render0-dev",
  "libxcb-shm0-dev",
  "libxcb-xfixes0-dev",
  "libxcb-randr0-dev",
  "libxcb-image0-dev",
  "libxcb-keysyms1-dev",
  "libxcb-icccm4-dev"
]

cmds = [
  "if [ ! -e /bin/bash ]; then ln -s /usr/bin/bash /bin/bash; fi"
]

[variables]
NIXPACKS_SHELL = "/bin/sh"
NIXPACKS_PATH = "/opt/venv/bin"
