[phases.setup]
nixPkgs = [
  "bash",
  "cairo",
  "pkg-config",
  "libxcb",
  "libXrender",
  "libXext",
  "libX11",
  "libXau",
  "libXdmcp"
]

[variables]
NIXPACKS_SHELL = "/bin/sh"
NIXPACKS_PATH = "/opt/venv/bin"
