[phases.setup]
aptPkgs = [
  "bash",
  "libcairo2-dev",
  "libxcb1-dev",
  "pkg-config"
]
cmds = [
  "if [ ! -e /bin/bash ]; then ln -s /usr/bin/bash /bin/bash; fi"
]

[variables]
NIXPACKS_SHELL = "/bin/sh"
NIXPACKS_PATH = "/opt/venv/bin"
