[phases.setup]
nixPkgs = [
  "bash",
  "cairo",
  "pkg-config",
  "xorg.libxcb",
  "xorg.libXrender",
  "xorg.libXext",
  "xorg.libX11",
  "xorg.libXau",
  "xorg.libXdmcp"
]

[variables]
NIXPACKS_SHELL = "/bin/sh"
NIXPACKS_PATH = "/opt/venv/bin"
